# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run:
          name: build the file
          command: |
            npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run:
          name: Print env name
          command: |
            npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Print env name
          command: |
            npm audit
workflows:
  # Name the workflow "welcome"
  my_pipeline:
    # Run the welcome/run job in its own container
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]